### ISSUE TITLE
iOS 10 and CallKit Support

### ISSUE THREAD

**Issue by powerqian** [BelledonneCommunications/linphone-iphone#104]
Hi Linphone developers,

Is there any plan for supporting iOS 10? I tried to use the latest commits in git repository as of today, and use Xcode 8 beta, iOS 10 SDK to run Linphone. The call can be established, but no audio or video. Meanwhile, in the console there's no log even after enabling all logs, so I can't find the reason why no audio myself.

In addition, iOS 10 has a very cool new framework, CallKit, for VoIP app to use. Any plan for adopting that as well?

**Comment by bagage** [comment]
Sure, we have to support it, but that's not done yet. We'll support it preferably before it gets released (check dev_ios10 branch).

**Comment by powerqian** [comment]
Nice to hear. No dev_ios10 branch in the git repo yet, though.

**Comment by powerqian** [comment]
I have to reopen this issue after spending a long time playing with CallKit.

The most troublesome thing I've encountered using the current liblinphone is that, the application cannot have the full control on the audio session and audio unit such as when to start or stop the audio unit. It results in all kinds of audio issue.

CallKit activate and deactivate the audio session for the application since it needs to coordinate with other calls, and according to the sample code provided by Apple, the applications that adopt the CallKit need to start the audio after CallKit activate the audio session, and stop the audio after CallKit deactivate the audio session. I've tried to
```
linphone_core_set_capture_device(theLinphoneCore, "AU: Audio Unit Fast Receiver");
linphone_core_set_playback_device(theLinphoneCore, "AU: Audio Unit Fast Receiver");
```
so that I can have the control over audio session configuration, but still in some kind scenario the call does not have sound (such as Hold&Answer a call) with no error log, but no audio output or input. I am thinking whether it is possible that liblinphone deactivate the audio session somehow.

Meanwhile there's another kind of case that may have the error log output as the following

```
<Notice>: lib/io unit initialized
<Notice>: lib/I/O unit latency [0.000000], quality [64]
2016-09-29 12:08:04.132434 frSIP-Mobile[961:244736] [aurioc] 889: failed: 'ent?' (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
<Error>: lib/AudioUnit error for (auresult = AudioOutputUnitStart(card->io_unit)): ret=unknown error (1701737535) (/path/to/linphone-iphone/submodules/linphone/mediastreamer2/src/audiofilters/msiounit.m:514)
<Notice>: lib/AudioUnit could not be started, current hw output latency [0.012063] input [0.000625] iobuf[0.011610] hw sample rate [44100.000000]
2016-09-29 12:08:04.240703 frSIP-Mobile[961:244736] [aurioc] 889: failed: 'ent?' (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
<Error>: lib/AudioUnit error for AudioUnitInitialize(card->io_unit): ret=unknown error (1701737535) (/path/to/linphone-iphone/submodules/linphone/mediastreamer2/src/audiofilters/msiounit.m:467)
```

I'm wondering is there a way to take full control over the audio such as active the audio session, configure the audio session, start/stop the audio unit, etc.? I guess you will encounter the similar issues when you keep exploring the CallKit integration, which quickly becomes a standard for iOS VoIP application now.

Any thoughts or comments are really appreciated.

**Comment by powerqian** [comment]
Another question is, are the following methods have any impact on the audio session?
```
linphone_core_start_dtmf_stream
linphone_core_stop_dtmf_stream
```
Since they are called every time the app become active and resign active, and in the CallKit, it will resign active when the native call screen shows, and become active when the call answers.

**Comment by alexvimodev** [comment]
@powerqian I am also getting same issue. Did you get any solution for this issue ?

**Comment by bagage** [comment]
Hey @powerqian, 
You should try to get in touch with Brieuc who's now in charge of iOS since I stopped working on Linphone several weeks ago. Keep the good work ;)

**Comment by powerqian** [comment]
@alexvimodev I've spent a lot time on this, digging into linphone's low level code, and I think currently there's no way to take control of the AudioUnit liblinphone uses on the application level. Since liblinphone is a cross platform call library, I think it will not have special treatment to iOS on the audio processing part. Our best chance is to let Linphone's developer be aware of this issue, and wait for their work around, if any. I might take another try in the future when I have time.

**Comment by powerqian** [comment]
Hey @bagage ,
I guess he is not so active on the GitHub as you do based on the activities in this project's Issue page... I do see him in the git's commit message, and will try to send a email. Hopefully he will reply...

Thank you again for your active help and response!

**Comment by Volkanugr** [comment]
is callkit working ? i see the branch but not checked

**Comment by powerqian** [comment]
@Volkanugr Linphone iPhone's CallKit implementation looks like making little progress.

**Comment by JFSene** [comment]
@powerqian I was about to start implementing CallKit when i saw your issue, I will give it a weeks work to see how far i can get it...i'll keep you all updated here

**Comment by powerqian** [comment]
@JFSene My biggest issue is the "Hold&Answer" handling. When there's an ongoing call, and receiving an incoming call, that button will show in the incoming call screen. After pressing that button, CallKit will send out Hold command for the first call, and Answer command for the second call. However, after processing them individually and successfully, the second call is answered with no audio.

Based on the call's bandwidth usage statistics 
```
RTP  audio=[d= 79.9,u=  0.8], video=[d=318.2,u=  1.0], text=[d=  0.0,u=  0.0] kbits/sec
RTCP audio=[d=  0.0,u=  0.8], video=[d=  0.0,u=  0.8], text=[d=  0.0,u=  0.0] kbits/sec
```
The call is connected, and receiving audio data, but does not playing it. Meanwhile the call is not recording any audio and sending.

My guess is that there is some place stopped the audio playback and recording. I've spent quite a long time on this issue, trying different things to the audio session, but still no luck...

**Comment by ennisthemenace** [comment]
Any progress ? :)

**Comment by ReisBenjamin** [comment]
Hi,

I believe the sound issues is fixed on the current version of Linphone iPhone.
As for CallKit, we have no plan to integrate it for now. If apple offers an API with a customizable UI we’ll consider integrating it.
However we propose an example of CallKit on the dev_callKit branch of our git repository. This example shows how to display and manage an Incoming call when the app is in background.
You can also find more info here : https://wiki.linphone.org/wiki/index.php/Getting-started:ios#CallKit_Integration

Best regards

**Comment by jiangzhibin** [comment]
@ReisBenjamin   @Brieuc
Thanks for your reply. 
Here are still some questions on dev_callKit:
The dev_callKit branch looks like not been finished. and bagage who's the author of dev_callKit did stop working on linphone-iphone, CallKit is a pretty good function, could you please improve it until it be done.

Best regards!

**Comment by ennisthemenace** [comment]
I have it working in my linphone with a few minor hickups now and then.

**Comment by jiangzhibin** [comment]
@ennisthemenace I also let it working in my project.
Here is a common scene: When I make a outgoing call by callkit, If some one calls me at the same time and I hold the callkit call, we can call linphone_core_pause_call to pause it,  after I decline the system incoming call, we can call linphone_core_resume_call to resume callkit outgoing call.
But here exist a issue, after linphone_core_pause_call the linphone_core_get_current_call, the linphone_core_get_current_call will return nil, I can't resume a call by linphone_core_resume_call the linphone_core_get_current_call.
Do you know how to resume a call?
It's appreciated for your help!

**Comment by powerqian** [comment]
@jiangzhibin You will need to have a key-value pair to bind the generated UUID, which is used by CallKit, to the LinphoneCall object. If you are using CallKit, all the actions are passed in by CallKit through its delegate with a CXCallAction, in which it contains the UUID.

By the way, for you guys who claimed to make it working, there's no any issue regarding Hold/Resume call? I always encounter no audio issue which is addressed above after Hold and Resume the call from time to time.

**Comment by jiangzhibin** [comment]
@powerqian  aha ，I always encounter no audio issue too, after debug, I found the linphone doesn't resume the call (linphone_core_resume_call(lc, linphone_core_get_current_call(lc));)  because the current call be nil after invoke linphone_core_pause_call.

Do you mean that we should hold/resume calls by CXCallAction? 
To my understanding, we should hold a call by CXCallAction just when user who click hold button from app UI.
 If we make a outgoing call by app, and receive a incoming call by system, then we hold the outgoing call and receive the system incoming call, callkit's delegate will calls "provider:(CXProvider *)provider performSetHeldCallAction:(CXSetHeldCallAction *)action", then we should mask the outgoing call's hold state to YES, and invoke the linphone's method "linphone_core_pause_call" to pause linphone's current call. after decline the system incoming call, we mask the outgoing call's hold state to NO, and  invoke linphone_core_resume_call to resume linphone's current call.
Any mistakes did I take?

**Comment by powerqian** [comment]
@jiangzhibin The correct way (according to the sample code provided by Apple) to integrate with CallKit is that, all the actions you make should be done by using `CXCallController` to call `requestTransaction:completion:` method, and wait for `CXProviderDelegate` to trigger corresponding delegate method, and do the actual work there.

For example, if you want to hold the call, what you need to do is

```
CXSetHeldCallAction *setHeldCallAction = [[CXSetHeldCallAction alloc] initWithCallUUID:UUID onHold:onHold];
CXTransaction *transaction = [[CXTransaction alloc] initWithAction:setHeldCallAction];
[self.callController requestTransaction:transaction completion:^(NSError * _Nullable error) {
    if (error) {
        NSLog(@"%@", error);
    }
}];
```

Then the CXProviderDelegate will trigger `provider:performSetHeldCallAction:`, and you call those linphone method inside that.

**Comment by jiangzhibin** [comment]
I know your meaning, as what you said,we should call requestTransaction:completion method,but the situation is that we make operation from our app, and we also know what did do by user.
there is another situation: app be held, it's no suitable time to requestTransaction:completion. system just calls CXProviderDelegate to tells us that our voip call was been held. we can call those linphone method inside it.

By the way, I make hold/resume working.
linphone_core_pause_call makes the current call to be nil, but we can find the call which been held in linphone_core_get_calls.
just like:
`LinphoneCore* lc = [LinphoneManager getLc];
    MSList *calls = (MSList *)linphone_core_get_calls(lc);
    while (calls) {
        LinphoneCallState state = linphone_call_get_state(calls->data);
        if (state == LinphoneCallPausing || state == LinphoneCallPaused) {
            linphone_core_resume_call(lc, calls->data);
            break;
        }
        calls = calls->next;
    }
`

**Comment by ReisBenjamin** [comment]
Try this code to find the call to pause :
LinphoneCall *currentCall = linphone_core_get_current_call(LC);
if (currentCall == nil && linphone_core_get_calls_nb(LC) == 1) {
	currentCall = (LinphoneCall *)linphone_core_get_calls(LC)->data;
}
return currentCall;

**Comment by jiangzhibin** [comment]
@powerqian 
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil]; can solves the mute issue.

**Comment by powerqian** [comment]
@jiangzhibin If you know the flow, then you know that in `provider:performSetHeldCallAction:`, it will give you a `CXSetHeldCallAction` as the second parameter, inside which it has the UUID of that action. You then use the UUID to find the LinphoneCall object which is paired with a UUID, and stored in a data structure when the UUID is created.

In the meantime, setting category does not completely solve my no audio issue mentioned above. As it seems no one encountered or tried to solve a similar issue, I tried to ask Apple's engineer about this topic. Will update it here if there's any progress.

**Comment by jiangzhibin** [comment]
@powerqian  YES, I pause the linphone-call when provider:performSetHeldCallAction: first be invoked,
and resume linphone-call when provider:performSetHeldCallAction: second be invoked, and all right.  
provider:performSetHeldCallAction: will be invoked twice if decline incoming call by myself. Otherwise,
if the system incoming call be decline by the caller,  provider:performSetHeldCallAction: only be invoked once, so I don't have a good time to resume the linphone-outgoing call. Any idea? thanks!

**Comment by ReisBenjamin** [comment]
@jiangzhibin Why do you want to set the call on hold or resume it if the call is declined ? If the call is declined you just need to terminate it.

@powerqian I have the same issue of no audio when call set on hold and resumed... I'm still looking for a solution, if I find one I'll post it here !

**Comment by Maleandr** [comment]
Hi, 
Don't you have issues with outgoing calls using callkit? I have calls without audio, when I try make calls fast.

I think this happen before audio session was deactivated and you try to make new call.

**Comment by powerqian** [comment]
@ReisBenjamin I'm so glad that you are working on it!! Sharing some of my findings in addition to no audio issue when hold and resume.
1. Similar to the case that @Maleandr mentioned, if you make a second call before the AudioUnit is destroyed, there will be no audio. The AudioUnit will be destroyed in a few seconds after the `provider:didDeactivateAudioSession:` notify the audio session is deactivated. I have to call `ms_snd_card_set_usage_hint(card, false)` to force the AudioUnit be destroyed right after. This can improve a little.
2. When the `maximumCallGroups` > 1, when the second call comes, if you choose "Hold&Answer", the second answered call will 100% have no audio.
3. There is several difference between the current Linphone implementation and the sample code. First, the audio session is actually never activated in the sample code. I guess the CallKit should handle the audio session activation and deactivation for us, and notify us through delegate. Second, the AudioUnit is not completely destroyed in the sample code, but in Linphone, when the call is paused, the AudioUnit is completely destroyed. Having said that, I actually tried to modify the code to be similar to the CallKit sample code by using `AU: Audio Unit Fast Receiver` as the play card and capture card, and not destroy AudioUnit. Unfortunately the result is still the same...

Looking forward to your solution!

**Comment by Maleandr** [comment]
Hi,

@powerqian exactly when do you call `ms_snd_card_set_usage_hint(card, false)`? After CallReleased linphone call state, on CallKit `provider:didDeactivateAudioSession:` or even sooner?

**Comment by powerqian** [comment]
@Maleandr on CallKit's `provider:didDeactivateAudioSession:`. Other places should work the same, though.

**Comment by Maleandr** [comment]
@powerqian Well `provider:didDeactivateAudioSession:` is called 1-2s after Linphone CallReleased. So there is some delay, which looks disrupting for me. Users cannot make call immediately after previous one.

**Comment by ReisBenjamin** [comment]
@Maleandr @powerqian I think I got it !
I only call linphone_core_pause_call and linphone_core_resume_call within the method provider:performSetHeldAction:

In the rest of the code I create CXSetHeldAction and request a transaction with them.
I have no audio problem but i'll continue testing it !

**Comment by Maleandr** [comment]
@ReisBenjamin did this helped you with no audio for outgoing calls?

**Comment by ReisBenjamin** [comment]
@Maleandr I never had an audio issue with outgoing call... So i don't know if it'll help.

**Comment by Maleandr** [comment]
@ReisBenjamin Did you tried to make outgoing calls really fast? I don't have issues, when I'm not too fast, but when i'm making calls really fast, some of them are without audio.

**Comment by powerqian** [comment]
@ReisBenjamin I was doing like that all along actually, still experiencing the audio issue from time to time (not every time, but in a great chance).

There's a slight modification of my implementation, though. I will wait for the call state change to the desired state, then fulfil the action, and go for the next action if any. This is needed based on my testing for some group actions like separate a call from conference, end and answer a call, etc. Anyway, maybe my approach is wrong.

In the meantime I don't think it will fix the audio issue in outgoing call mentioned by @Maleandr. If you see the log, as long as a new call is made before the first call's "AudioUnit is stopped. AudioUnit is destroyed." shows, the new call won't have audio.

**Comment by henrik415** [comment]
@Maleandr I too have no audio in outgoing calls. Incoming call has audio, no issue there.
Please let me know if you manage to find the reason. I'll keep you posted if I find something.

**Comment by Maleandr** [comment]
I was able to get around problem with outgoing call by using:
`// Signal to the system that the action has been successfully performed.
        let audioSession = AVAudioSession.sharedInstance()
        
        do {
            try audioSession.setCategory(AVAudioSessionCategoryPlayAndRecord)
            try audioSession.setMode(AVAudioSessionModeVoiceChat)
            try audioSession.setPreferredSampleRate(44100)
            try audioSession.setPreferredIOBufferDuration(0.005)
        } catch {
            print(error)
            Logger.logData("Failed to init audio session")
        }
        
         linphone_core_reload_sound_devices(LinphoneManager.getLc())`

in provider method ` provider(_ provider: CXProvider, perform action: CXStartCallAction`. There is small delay before every call is made (cca 1s), but that is far more acceptable than other solutions. I'm not sure if it is best solution, kind off looks like brute force, but it works for now.

**Comment by henrik415** [comment]
Calling `linphone_core_reload_sound_devices()` causes a crash in MS2 due to a race condition where an audio unit is both created and destroyed from two different threads.
I am using slightly older version of MS2 (from this spring), does anyone know if this is a know issue fixed in later releases?

**Comment by ReisBenjamin** [comment]
Hi everyone !
I believe I fixed the problem in commit a441ae7b138fdfc03c67f0880d332de330864632.
The issue was in the SDK. And so there's no need to mess with the AVAudioSession.
Please let me know if it works for you too.

**Comment by Maleandr** [comment]
@ReisBenjamin This solves which issues call pause/resume, outgoing call or both?

**Comment by ReisBenjamin** [comment]
@Maleandr Oops forgot to precise... Outgoing calls with no audio.

**Comment by jiangzhibin** [comment]
@powerqian  I was in trouble with Speaker button, I click the Speaker button when answer a incoming call, the callkit wouldn't callback with any delegate method, how can I make it work,Looking forward to your solution!

**Comment by ReisBenjamin** [comment]
@jiangzhibin Yes it is a known issue. I think it's an Apple error because callkit speaker button can't be controlled from the app and this behavious appears on other apps using callkit...
Hopefully it'll be fixed in a future update !

**Comment by Maleandr** [comment]
@ReisBenjamin It works for me. Thank you for fix! :)

**Comment by eliburke** [comment]
@powerqian @Maleandr @jiangzhibin @henrik415 Are any of you willing to share any code or details of your CallKit implementations? Are you using @ReisBenjamin 's ProviderDelegate sample, or the earlier ADCallKitManager or something else?

**Comment by henrik415** [comment]
@eliburke I'm still having an issue with outgoing audio but I'm still on a fairly old LinphoneCore release. I've adapted ADCallKitManager to suit my needs and I can share my work once I rebased to latest release (and get it working).

**Comment by Maleandr** [comment]
@ReisBenjamin Another question...Don't you have issues with ring tone? I don't know why but it is not played every time.

**Comment by ReisBenjamin** [comment]
Hello @Maleandr,

Hum... No I've never had an issue with the ringtone... Did you set it when you configure Callkit with :
CXProviderConfiguration *config = [[CXProviderConfiguration alloc] initWithLocalizedName:@"Linphone"];
	config.ringtoneSound = @"shortring.caf";
	self.provider = [[CXProvider alloc] initWithConfiguration:config];

**Comment by Maleandr** [comment]
@ReisBenjamin Yes I have it in configuration. Problem is that sometime it is played and sometimes not. Problem is usually after declining call.

**Comment by eliburke** [comment]
@henrik415 @Maleandr I have made some progress with my integration, but I have a problem when launching from the lock screen. If my app is in the background and a call comes in, clicking the Accept button switches to my app which triggers Registration and then I get the Incoming Call.

On the other hand, if the device is locked I have Swipe to Unlock, and then tap another button to launch my app. Do either of you know if there a way to skip this step and open the application immediately (this is necessary because of a requirement to have a secondary PIN lock).

**Comment by Maleandr** [comment]
@eliburke No i don't know any way how skip this tep

**Comment by Maleandr** [comment]
@ReisBenjamin Is there any possibility that linphone ring tone is interfering with call kit ring tone?

**Comment by ReisBenjamin** [comment]
@eliburke I don't think either that it's possible to skip the CallKit view when the device is locked as it'd need to bypass the PIN to unlock the screen.

@Maleandr I'm not sure, I don't reproduce this issue but I'll try to investigate.

**Comment by ReisBenjamin** [comment]
Hello,

Since it's not active anymore i'll close this issue.
Do not hesitate to reopen if a problem occur.
I just want to point that in the commit "Refactor of CallKit" I've changed the philosophy of the implementation. Now we start, accept and resume a call only when Callkit has activated the Audio Session. And there is no more sound issue for me.
Hope it helps !

**Comment by Maleandr** [comment]
Hi @ReisBenjamin,

Does callkit handle ringing for you correctly? I still have issues with ringing. It works sometimes, but after some random time if stops. No idea what is wrong. I have updated to newest ios lib, but the issue persists. I'm waiting for session activation, before doing any call accepting.

**Comment by ReisBenjamin** [comment]
Hello,

No I do not encounter this issue.
I've tried to call Linphone on fore ground, back ground and when app is killed with and without lockscreen and it rings everytime.

**Comment by Maleandr** [comment]
It rings for you even on lockscreen? Hmm I'm doing something wrong then. I checked code and you are setting ringing sound for linphone lib - i'm not doing it, because callkit should handle ringing right?

Do you have any idea, where can be error? I'm setting ringing sound for provider in config. I'm not aware about any other place, where I should set something.

**Comment by Artimuss** [comment]
Hi !

We have a media problem on end and accept. When we are in GSM call and we receive a call in our app, if we choose "Hold and accept" it's ok but if we choose "End and accept", we haven't got any media...

Any ideas ?

**Comment by ReisBenjamin** [comment]
Hello,

This issue has been closed, please open a new one for future question/problem.
As for your question : you need to wait for the audio session to be activated by callkit to start (and resume as well) the call. If not you're media will be stopped by the activation.
This issue as been addresses in linphone-iphone you can update your code to our last relase (3.16.2) to obtain this fixes.

Best regards,
Benjamin
