### ISSUE TITLE
Disable requests to associate the number with linphone.org

### ISSUE THREAD

**Issue by anatoli26** [BelledonneCommunications/linphone-iphone#193]
Is it possible to disable constant requests for the number association with the linphone.org service? It would be nice to have an option to completely disable linphone.org options, i.e. once the app is configured, it doesn't bother the user with strange questions, nor shows confusing options when the app is configured e.g. with an account on a corporate SIP server.

**Comment by ReisBenjamin** [comment]
fixed in commit 9b57a315647f92bce6cf4b0b30f221af1e2c6376

**Comment by anatoli26** [comment]
@ReisBenjamin, just got again the offer to link my **non**-linphone.org account to my phone number (though the offer said "link your linphone.org account"). This is after the latest update 2 days ago. Also, I'm not seeing the option to disable contacts uploading to linphone.org servers as was discussed in the mailinglist.

Does that mean that the latest version doesn't include these changes?

- Linphone iOS 3.16.2
- Linphone Core 3.10.2-852-ga462773

**Comment by ReisBenjamin** [comment]
Hello @anatoli26, these fixes have been added after our beta launch so they are not available into the last release but will be in the next.
If you want to have these features you can either build our latest sources or wair for our next beta.

Regards

**Comment by anatoli26** [comment]
Thanks for the clarification, Benjamin.

**Comment by anatoli26** [comment]
@ReisBenjamin, when do you expect to release a new version? The problem of the pop-up asking to link the account is still present in the latest 3.16.2, also I imagine the privacy issue of uploading the contacts is also still not released, right?

**Comment by ReisBenjamin** [comment]
Hello,

The will release the new version within the week normally.
Regards
