### ISSUE TITLE
Incorrect handling of "Call completed elsewhere" CANCEL cause (RFC 3326)

### ISSUE THREAD

**Issue by anatoli26** [BelledonneCommunications/linphone-iphone#309]
When calling multiple endpoints at the same time, if one endpoint answers the call, a typical PBX sends a `CANCEL` to the other endpoints that were ringing with a cause `"Call completed elsewhere"` (this is according to the RFC 3326). Here is an example:

```
CANCEL sip:110@192.168.0.18;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.0.1;rport;branch=z9hG4bKXvHpSSgN3m65Q
Max-Forwards: 70
From: <sip:111@192.168.0.1>;tag=3831947110
To: <sip:110@192.168.0.18;transport=udp>
Call-ID: kszvxsBXFD
CSeq: 1114104451 CANCEL
Reason: SIP;cause=200;text="Call completed elsewhere"
Content-Length: 0
```

But Linphone, when receiving this message, shows a missed call in the call history when it should have shown an answered call.

Same behavior on both mobile versions iOS and Android.

Similar behavior is observed in Linphone 4 desktop, but there is no single call history, so it's not that noticeable, but in the per-contact call history, the answered call nevertheless appears as "missed".

**Comment by ReisBenjamin** [comment]
Hello,

This should be fixed since commit 594fb5f0e02f0ec6ef91401f1eac59b8e4cb17f9.
Is your code up to date ?

Thanks

**Comment by anatoli26** [comment]
Hi Reis,

On iPhone 6S with iOS 11 I have the latest Linphone iOS 3.16.4 according to AppStore, though the app in _About_ shows "Linphone iOS 3.16.3". In this repo I see this is the latest version (3.16.**4**) and it was published some 4 months ago. If I haven't missed something, I guess the commit you're referring to was not published yet.

Something similar happens with Linphone on Android, though there the About and PlayStore versions match: 3.2.7, also released in May.

**Comment by ReisBenjamin** [comment]
Hello,

Indeed this commit is not yet available on the AppStore, it will be integrated in our next release.
However it's available on the current master branch of our git repo

**Comment by anatoli26** [comment]
Thanks Benjamin, I'll close the issue now and if the new release doesn't solve the problem, I'll reopen it. Do you have an ETA for the new release?
